name: flutter_lqrui
description: A new flutter plugin project.
version: 0.0.1
author: lqrui
homepage:

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_picker: ^1.1.0 #选择器
  # multi_image_picker: ^4.5.9 #多图片选择
  multi_image_picker: ^4.6.0-rc.3
  image_picker: ^0.6.2 #图片选择，相册或拍照
  file_picker: ^1.4.3+1 #文件选择
  flustars: ^0.2.6+1 #Flutter常用工具类库
  fluttertoast: ^3.1.3 #Toast轻提示
  uuid: ^2.0.4
  flutter_spinkit: ^4.1.0 #加载动画指示器
  flutter_easyrefresh: ^2.0.5 #上拉加载
  # cached_network_image: ^1.1.3 #缓存图片
  cached_network_image: ^2.0.0-rc
  url_launcher: ^5.4.0 #链接跳转 
  dio: ^3.0.7 #ajax 
  photo_view: ^0.9.0  #图片预览
  flutter_swiper: ^1.1.6 #swiper
  provider: ^3.2.0 #全局变量
  flutter_slidable: ^0.5.4 #滑动显示操作按钮
  charts_flutter: ^0.8.1 #谷歌图表
  package_info: ^0.4.0+4 #获取本地版本 

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: com.example.flutter_lqrui
    pluginClass: FlutterLqruiPlugin
    
