name: flutter_lqrui
description: A new flutter plugin project.
version: 0.0.1
author: lqrui
homepage:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_picker: ^1.1.0 #选择器
  multi_image_picker: ^4.6.1
  image_picker: ^0.6.3 #图片选择，相册或拍照
  file_picker: ^1.4.3+1 #文件选择
  flustars: ^0.2.6+1 #Flutter常用工具类库
  fluttertoast: ^3.1.3 #Toast轻提示
  uuid: ^2.0.4
  flutter_spinkit: ^4.1.2 #加载动画指示器
  flutter_easyrefresh: ^2.0.9 #上拉加载
  # cached_network_image: ^1.1.3 #缓存图片
  cached_network_image: ^2.0.0
  url_launcher: ^5.4.2 #链接跳转 
  dio: ^3.0.9 #ajax 
  photo_view: ^0.9.2  #图片预览
  flutter_swiper: ^1.1.6 #swiper
  provider: ^4.0.4 #全局变量
  flutter_slidable: ^0.5.4 #滑动显示操作按钮
  charts_flutter: ^0.9.0 #谷歌图表
  package_info: ^0.4.0+4 #获取本地版本

  inn_router:
    path: ../inn_router

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: com.example.flutter_lqrui
    pluginClass: FlutterLqruiPlugin
    
